# Generated by Django 5.0.3 on 2024-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_name', '0002_topic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='team',
            field=models.CharField(default='team_india', max_length=100),
        ),
    ]
